name: C test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      run: make
    - name: test
      run: ./mexel input_nested.csv
